name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21'

      - name: build game
        run: |
          git clone https://github.com/tmedwards/tweego.git
          cd tweego
          go mod download github.com/Masterminds/semver/v3
          go get github.com/tmedwards/tweego
          cd ../
          export PATH=$PATH:$(go env GOPATH)/bin
          tweego dialogue -o dist/index.html

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist