name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build dialogue
        run: |
          wget https://github.com/tmedwards/tweego/releases/download/v2.1.1/tweego-2.1.1-linux-x64.zip
          unzip -j tweego-2.1.1-linux-x64.zip tweego
          chmod +x tweego
          ./tweego dialogue -o dist/index.html

      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist

permissions:
  contents: write